development:
  adapter: mysql2
  host: localhost
  database: simple_roles_development
  username: root 
  password: root
  encoding: utf8

test:
  adapter: mysql2
  host: localhost
  database: simple_roles_test
  username: root
  password: root
  encoding: utf8

production:
  adapter: mysql2
  host: localhost
  port: 5432
  database: simple_roles_production
  username: pgsql 
  password: pgsql 
  schema_search_path: public
  encoding: utf8
  template: template0
