development:
  adapter: mysql2
  host: localhost
  database: simple_roles_development
  username: root 
  password:
  encoding: utf8

test:
  adapter: mysql2
  host: localhost
  database: simple_roles_test
  username: root
  password:
  encoding: utf8
